# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

Region.create(name_region: 'Republic of Adygea (Adygea)', code_region: '01')
Region.create(name_region: 'Republic of Bashkortostan', code_region: '02')
Region.create(name_region: 'Republic of Buryatia', code_region: '03')
Region.create(name_region: 'Altai Republic', code_region: '04')
Region.create(name_region: 'Republic of Dagestan', code_region: '05')
Region.create(name_region: 'Republic of Ingushetia', code_region: '06')
Region.create(name_region: 'Kabardino-Balkarian Republic', code_region: '07')
Region.create(name_region: 'Republic of Kalmykia', code_region: '08')
Region.create(name_region: 'Karachay-Cherkess Republic', code_region: '09')
Region.create(name_region: 'Republic of Karelia', code_region: '10')
Region.create(name_region: 'Komi Republic', code_region: '11')
Region.create(name_region: 'Republic of Mari El', code_region: '12')
Region.create(name_region: 'Republic of Mordovia', code_region: '13')
Region.create(name_region: 'Republic of Sakha (Yakutia)', code_region: '14')
Region.create(name_region: 'Republic of North Ossetia — Alania', code_region: '15')
Region.create(name_region: 'Republic of Tatarstan (Tatarstan)', code_region: '16')
Region.create(name_region: 'Republic of Tyva', code_region: '17')
Region.create(name_region: 'Udmurt Republic', code_region: '18')
Region.create(name_region: 'Republic of Khakassia', code_region: '19')
Region.create(name_region: 'Chechen Republic', code_region: '20')
Region.create(name_region: 'Chuvash Republic — Chuvashia', code_region: '21')
Region.create(name_region: 'Altai region', code_region: '22')
Region.create(name_region: 'Krasnodar Territory', code_region: '23')
Region.create(name_region: 'Krasnoyarsk Territory', code_region: '24')
Region.create(name_region: 'Primorsky Krai', code_region: '25')
Region.create(name_region: 'Stavropol Territory', code_region: '26')
Region.create(name_region: 'Khabarovsk Territory', code_region: '27')
Region.create(name_region: 'Amur region', code_region: '28')
Region.create(name_region: 'Arkhangelsk region', code_region: '29')
Region.create(name_region: 'Astrakhan region', code_region: '30')
Region.create(name_region: 'Belgorod region', code_region: '31')
Region.create(name_region: 'Bryansk region', code_region: '32')
Region.create(name_region: 'Vladimir region', code_region: '33')
Region.create(name_region: 'Volgograd region', code_region: '34')
Region.create(name_region: 'Vologda region', code_region: '35')
Region.create(name_region: 'Voronezh region', code_region: '36')
Region.create(name_region: 'Ivanovo region', code_region: '37')
Region.create(name_region: 'Irkutsk region', code_region: '38')
Region.create(name_region: 'Kaliningrad region', code_region: '39')
Region.create(name_region: 'Kaluga region', code_region: '40')
Region.create(name_region: 'Kamchatka Krai', code_region: '41')
Region.create(name_region: 'Kemerovo Region — Kuzbass', code_region: '42')
Region.create(name_region: 'Kirov region', code_region: '43')
Region.create(name_region: 'Kostroma region', code_region: '44')
Region.create(name_region: 'Kurgan region', code_region: '45')
Region.create(name_region: 'Kursk region', code_region: '46')
Region.create(name_region: 'Leningrad region', code_region: '47')
Region.create(name_region: 'Lipetsk region', code_region: '48')
Region.create(name_region: 'Magadan region', code_region: '49')
Region.create(name_region: 'Moscow region', code_region: '50')
Region.create(name_region: 'Murmansk region', code_region: '51')
Region.create(name_region: 'Nizhny Novgorod region', code_region: '52')
Region.create(name_region: 'Novgorod region', code_region: '53')
Region.create(name_region: 'Novosibirsk region', code_region: '54')
Region.create(name_region: 'Omsk region', code_region: '55')
Region.create(name_region: 'Orenburg region', code_region: '56')
Region.create(name_region: 'Oryol region', code_region: '57')
Region.create(name_region: 'Penza region', code_region: '58')
Region.create(name_region: 'Perm Region', code_region: '59')
Region.create(name_region: 'Pskov region', code_region: '60')
Region.create(name_region: 'Rostov region', code_region: '61')
Region.create(name_region: 'Ryazan region', code_region: '62')
Region.create(name_region: 'Samara region', code_region: '63')
Region.create(name_region: 'Saratov region', code_region: '64')
Region.create(name_region: 'Sakhalin region', code_region: '65')
Region.create(name_region: 'Sverdlovsk region', code_region: '66')
Region.create(name_region: 'Smolensk region', code_region: '67')
Region.create(name_region: 'Tambov region', code_region: '68')
Region.create(name_region: 'Tver region', code_region: '69')
Region.create(name_region: 'Tomsk region', code_region: '70')
Region.create(name_region: 'Tula region', code_region: '71')
Region.create(name_region: 'Tyumen region', code_region: '72')
Region.create(name_region: 'Ulyanovsk region', code_region: '73')
Region.create(name_region: 'Chelyabinsk region', code_region: '74')
Region.create(name_region: 'Trans-Baikal Territory', code_region: '75')
Region.create(name_region: 'Yaroslavl region', code_region: '76')
Region.create(name_region: 'Moscow', code_region: '77')
Region.create(name_region: 'Saint Petersburg', code_region: '78')
Region.create(name_region: 'Jewish Autonomous Region', code_region: '79')
Region.create(name_region: 'Nenets Autonomous Okrug', code_region: '83')
Region.create(name_region: 'Khanty-Mansi Autonomous Okrug — Yugra', code_region: '86')
Region.create(name_region: 'Chukotka Autonomous Okrug', code_region: '87')
Region.create(name_region: 'Yamalo-Nenets Autonomous Okrug', code_region: '89')
Region.create(name_region: 'Other territories, including the city and the Baikonur cosmodrome', code_region: '99')
